##
# Document structure and metadata specification for institutodourados.org
#
# Author: Matt Turner
# Date: 25 June 2026
#

project:
  type: website



website:
  title: "Instituto Dourados"

  favicon: sticker-favicon.jpg

  page-footer:
    left: |
      [Accessibility](/accessibility.qmd) · [Privacy](/privacy.qmd)
    center: |
      © 2026 Instituto Dourados, California
    right: |
      [Contact](mailto:contato@institutodourados.org)

languages:
  pt:
    name: Português
    dir: pt
    default: true
  en:
    name: English
    dir: en

format:
  html:

    toc: true
    number-sections: false
    # Navigation between languages is partly handled in css
    css: langnav.css
    # Custom HTML for the header, not Quarto/Boostrap default
    include-in-header: header.html

    theme:
      light:
        - styles.scss
        - theme-light.scss
      dark:
        - darkly
        - styles.scss
        - theme-dark.scss
    fontsize: 1.1em
    linestretch: 1.4
    number-depth: 3

bibliography: dourados.bib
